### ISSUE TITLE
能整个备份脚本么

### ISSUE THREAD

**Issue by luodaoyi** [teddysun/lcmp#4]
一键备份 /data/www和数据库还有caddy的配置？
然后装了新环境在整个一键导入？

**Comment by AnneOoh** [comment]
若只是備份的話
大可借用一下軍哥的 backup.sh 脚本

不過需要修改
MySQL_Dump="/usr/local/mysql/bin/mysqldump"
為
MySQL_Dump="/usr/bin/mariadb-dump"

其它的配置，根據脚本中的説明做修改。

**Comment by luodaoyi** [comment]
军哥脚本被挂马了 不敢用啊

**Comment by AnneOoh** [comment]
> 军哥脚本被挂马了 不敢用啊
只用軍哥的備份脚本就好了，代碼自己審計。
https://github.com/lnmpkvemail/lnmp/blob/master/tools/backup.sh

另外，秋水大佬的 LAMP 中的也有備份脚本，也能借用。
https://github.com/teddysun/lamp/blob/master/backup.sh

**Comment by teddysun** [comment]
没错，备份脚本是可以通用的。
https://github.com/teddysun/lamp/blob/master/backup.sh
