### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by bibicadotnet** [teddysun/lcmp#9]
![2024-07-29_03-26-52](https://github.com/user-attachments/assets/8aaf3f7f-3118-4e3f-a2cf-a27883488590)

Some demo images

![2024-07-29_03-47-23](https://github.com/user-attachments/assets/fac1a8b3-699b-41eb-8202-c128a429d368)

**Comment by moewhale** [comment]
> ![2024-07-29_03-26-52](https://private-user-images.githubusercontent.com/119997727/352866506-8aaf3f7f-3118-4e3f-a2cf-a27883488590.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDQ3MDcsIm5iZiI6MTcyMjQwNDQwNywicGF0aCI6Ii8xMTk5OTc3MjcvMzUyODY2NTA2LThhYWYzZjdmLTMxMTgtNGUzZi1hMmNmLWEyNzg4MzQ4ODU5MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwNTQwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTU3NjU0MDlkYmVmYWE5MDIxYmI0ZTA0YjZkYjU2OWQxYzdiYjU2MTA3Yzg1ZWQwYzg3YzU1ZDU3OGQ2MDE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LgR5kDas8MfxvfD2SakhAIgJl0v6BOFUdkazC5AdOno)
> 
> Some demo images
> 
> ![2024-07-29_03-47-23](https://private-user-images.githubusercontent.com/119997727/352866537-fac1a8b3-699b-41eb-8202-c128a429d368.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDQ3MDcsIm5iZiI6MTcyMjQwNDQwNywicGF0aCI6Ii8xMTk5OTc3MjcvMzUyODY2NTM3LWZhYzFhOGIzLTY5OWItNDFlYi04MjAyLWMxMjhhNDI5ZDM2OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwNTQwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzhlNjUxNjg0ZmFkMjBkMGQ2YjhhYjRhNTZhYTg0ZmUxNzQ4MTdjYjk1MWNmOGNmMzBhY2UxOTQxNjgzYmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qpAQX8yIot1gnc6sC9uyWlN84pzmxtiqxGuovUguDOc)

https://github.com/teddysun/lcmp/issues/7#issuecomment-2230650207

**Comment by bibicadotnet** [comment]
> PHP-8.3 missing lz4 [#7 (comment)](https://github.com/teddysun/lcmp/issues/7#issuecomment-2230650207)

Thanks
